# Generated by Django 2.2.7 on 2020-05-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_Func', models.CharField(blank=True, max_length=120, null=True)),
                ('grade', models.TextField(default='6', max_length=2)),
                ('jobFamily', models.CharField(max_length=120)),
                ('midpoint', models.IntegerField(default='100000')),
                ('STI', models.IntegerField(default='10', max_length=2)),
                ('superannuation', models.IntegerField()),
                ('region', models.CharField(default='MinAus', max_length=120)),
            ],
        ),
    ]
