# Generated by Django 2.2.7 on 2020-05-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rem',
            name='asset_Func',
            field=models.CharField(blank=True, choices=[('NiW', 'NiW'), ('WAIO', 'WAIO')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='rem',
            name='grade',
            field=models.TextField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], default='6', max_length=2),
        ),
        migrations.AlterField(
            model_name='rem',
            name='region',
            field=models.CharField(choices=[('MinAus', 'MinAus'), ('MinAm', 'MinAm'), ('Functions', 'Functions'), ('Petroleum', 'Petroleum')], default='MinAus', max_length=120),
        ),
    ]
